/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevenirRepetiteurRouteImport } from './routes/devenir-repetiteur'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as TrouverUnRepetiteurRouteImport } from './routes/trouver-un-repetiteur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirRepetiteurRoute = DevenirRepetiteurRouteImport.update({
  id: '/devenir-repetiteur',
  path: '/devenir-repetiteur',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const TrouverUnRepetiteurRoute = TrouverUnRepetiteurRouteImport.update({
  id: '/trouver-un-repetiteur',
  path: '/trouver-un-repetiteur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/devenir-repetiteur': typeof DevenirRepetiteurRoute
  '/faq': typeof FaqRoute
  '/trouver-un-repetiteur': typeof TrouverUnRepetiteurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/devenir-repetiteur': typeof DevenirRepetiteurRoute
  '/faq': typeof FaqRoute
  '/trouver-un-repetiteur': typeof TrouverUnRepetiteurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/contact': typeof ContactRoute
  '/devenir-repetiteur': typeof DevenirRepetiteurRoute
  '/faq': typeof FaqRoute
  '/trouver-un-repetiteur': typeof TrouverUnRepetiteurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/contact'
    | '/devenir-repetiteur'
    | '/faq'
    | '/trouver-un-repetiteur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/contact'
    | '/devenir-repetiteur'
    | '/faq'
    | '/trouver-un-repetiteur'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/comment-ca-marche'
    | '/contact'
    | '/devenir-repetiteur'
    | '/faq'
    | '/trouver-un-repetiteur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ContactRoute: typeof ContactRoute
  DevenirRepetiteurRoute: typeof DevenirRepetiteurRoute
  FaqRoute: typeof FaqRoute
  TrouverUnRepetiteurRoute: typeof TrouverUnRepetiteurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-repetiteur': {
      id: '/devenir-repetiteur'
      path: '/devenir-repetiteur'
      fullPath: '/devenir-repetiteur'
      preLoaderRoute: typeof DevenirRepetiteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trouver-un-repetiteur': {
      id: '/trouver-un-repetiteur'
      path: '/trouver-un-repetiteur'
      fullPath: '/trouver-un-repetiteur'
      preLoaderRoute: typeof TrouverUnRepetiteurRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ContactRoute: ContactRoute,
  DevenirRepetiteurRoute: DevenirRepetiteurRoute,
  FaqRoute: FaqRoute,
  TrouverUnRepetiteurRoute: TrouverUnRepetiteurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
